//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.5466
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortnoxAPILibrary
{
    public interface ISearchResult : IDummyInterface
    {
        string TotalResources { get; set; }
        string TotalPages { get; set; }
        string CurrentPage { get; set; }
    }
}